### ISSUE TITLE
Can't init secrets store

### ISSUE THREAD

**Issue by pavel-main** [kisom/cryptutils#4]
Hi, very nice idea for a CLI-app, but, when I'm trying to init `secrets` store, I get the error:

```
$ secrets -init
2015/05/02 21:21:41 The handle is invalid.
```

Can't even find this kind of error message in the project, to prepare a fix, any help?
OS/Arch: Windows 7 x64

**Comment by kisom** [comment]
If I had to guess, I think the password prompt is the problem; it seems to be a [known problem](http://grokbase.com/t/gg/golang-nuts/15476tgv97/go-nuts-building-go-project-panic-the-handle-is-invalid) with the `ssh` package that I use to read the password. I don't have a windows machine to test with, though.

**Comment by kisom** [comment]
Can you run `go test github.com/kisom/cryptutils/common/...` and let me see the results? It might give me some more information.

**Comment by ai-pavel** [comment]
Here you go

```
$ go test github.com/kisom/cryptutils/common/...
ok      github.com/kisom/cryptutils/common/auth 10.713s
?       github.com/kisom/cryptutils/common/auth/examples/login  [no test files]
ok      github.com/kisom/cryptutils/common/public       152.190s
ok      github.com/kisom/cryptutils/common/secret       79.528s
?       github.com/kisom/cryptutils/common/store        [no test files]
ok      github.com/kisom/cryptutils/common/tlv  0.446s
--- FAIL: TestExists (0.00s)
        util_test.go:110: util: Exists should fail to check the test file
[!] testing Errorf
[!] testing Errorf
--- FAIL: TestReadFile (0.00s)
        util_test.go:154: util: expect SHA-256 digest of '43510aeb890cc65fefbf464fd2c0fc748c5b30fe53d22a907bad6a8cbdfd22d2', but have '2baff7d1d6d5e5fcdc0b0a00cec6ac9e16dc5801526b59b76e8420d25ab763fc'
Do not go gentle into that good night
Old age should burn and rave at close of day
Rage, rage against the dying of the light.
test prompt: test prompt:
FAIL
FAIL    github.com/kisom/cryptutils/common/util 0.854s
```

**Comment by kisom** [comment]
Well, it looks like the Windows side is broken. I'll have to figure out a way to test and debug this on my end.
