### ISSUE TITLE
Fail to Unmarshal Private

### ISSUE THREAD

**Issue by florianlenz** [kisom/cryptutils#6]
Hi,

is there a way to convert a private key created by the official [ed25519](https://godoc.org/golang.org/x/crypto/ed25519) package to the private key provided by the [`common/public`](https://github.com/kisom/cryptutils/blob/master/common/public/crypto.go#L30) package.

**Comment by kisom** [comment]
The private key used by the `common/public` is a hybrid key that [contains both a `curve25519` and `ed25519` key](https://godoc.org/github.com/kisom/cryptutils/common/public#PrivateKey). So you could fill out the `S` and `V` fields with the keypair from the `ed25519` package, but you still need to provide an encryption key (ed25519 just provides a signing key). You can see how this is done [here](https://github.com/kisom/cryptutils/blob/master/common/public/crypto.go#L219).

**Comment by florianlenz** [comment]
@kisom Thanks.
