### ISSUE TITLE
oath.go and totp.go don't build

### ISSUE THREAD

**Issue by pepa65** [kisom/cryptutils#8]
Both complain that qr must be imported as rsc/qr.
`oath.go:9:2: must be imported as rsc/qr`
`../common/auth/totp.go:19:2: must be imported as rsc/qr`

I don't know how to fix this.
(I'm trying to build otpc.)

**Comment by kisom** [comment]
Hello, @pepa65! Thanks for the bug report. I think I’ve sorted this out; can you pull master and try again? Thanks!

**Comment by pepa65** [comment]
Great, thank you, it's building now!
