### ISSUE TITLE
Can't remove secrets/meta-data

### ISSUE THREAD

**Issue by juztin** [kisom/cryptutils#9]
Still using `secrets-cli` after all of these years, and my db is getting a bit polluted with old/outdated secrets/meta-data.
It'd be super nice to be able to clear out some of these old entries without creating a brand new store.

I've got everything implemented to remove both secrets & meta-data, would you be up for a PR for this?

**Comment by kisom** [comment]
I saw you closed it; Github didn't send me a notification. Are you still running into this?
